### PR TITLE
Fix.diacritics

### LINKED ISSUE #3: RemoveDiacritics does not deal well with certain characters
Precisely ØøæÆœŒ

### PR DESCRIPTION
**Pull request by nfaugout**
Resolves #3

NB : you should review commits individually due to tabs replacement

### CODE REVIEW

File: NExtends/Primitives/String.extensions.cs [hunk 1]
```diff
@@ -9,555 +9,577 @@
...
+                return false;
+            }
+
+            return true;
+        }
+
+        /// <summary>
+        /// On passe par un MailAddress, plus simple
+        /// </summary>
+        public static bool isEmail(this string email)
```
Comment (rducom) [inline NExtends/Primitives/String.extensions.cs]: It could be nice to introduce IsEmail with i capital letter, and obsolete this one. (code convention)

File: NExtends/Primitives/String.extensions.cs [hunk 2]
```diff
@@ -9,555 +9,577 @@
...
+                    stringBuilder.Append(c);
+                }
+            }
+
+            return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
+        }
+
+        public static string RemoveSpecialCaracters(this string text)
+        {
+            return Regex.Replace(text, @"[^a-zA-Z]+", "");
```
Comment (rducom) [inline NExtends/Primitives/String.extensions.cs]: There's place for performance improvement here ! :) Maybe in another PR

File: NExtends/Primitives/String.extensions.cs [hunk 3]
```diff
@@ -9,555 +9,577 @@
...
+        }
+
+        /// <summary>
+        /// Annee10 => 10
+        /// Annee => 1
+        /// </summary>
+        /// <param name="str"></param>
+        /// <param name="defaultValue (optional)"></param>
+        /// <returns></returns>
+        public static int GetOperand(this string str, int defaultValue = 1)
```
Comment (rducom) [inline NExtends/Primitives/String.extensions.cs]: don't understand this one. Still used ?

Comment (rducom) [reply NExtends/Primitives/String.extensions.cs]: Indeed, all the "Operand" methods are non generic ones, it's seems specific to a special functional case. I think we should remove them

File: NExtends/Primitives/String.extensions.cs [hunk 4]
```diff
@@ -9,555 +9,577 @@
...
+        static Regex isGuid = new Regex(@"^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$", RegexOptions.Compiled);
+
+        //Validation des numéro de sécu INSEE
+        //version de gabsoftware
+        //http://www.developpez.net/forums/d677820/php/langage/regex/verification-numero-securite-sociale/
+        private const string REGULAR_INSEE_NUMBER = @"([1-3])[\s\.\-]?(\d{2})[\s\.\-]?(0\d|[2-35-9]\d|[14][0-2])[\s\.\-]?(0[1-9]|[1-9]\d|2[abAB])[\s\.\-]?(\d{3})[\s\.\-]?(\d{3})[\s\.\-\|]{0,3}";
+        private const string TEMPORARY_INSEE_NUMBER = @"(?<temp>[7-9][\s\.\-]?\d{2}[\s\.\-]?\d{2}[\s\.\-]?\d{2}[\s\.\-]?\d{3}[\s\.\-]?\d{3}[\s\.\-\|]?)";
+        private const string KEY_INSEE_NUMBER = @"(?<key>[0-8]\d|9[0-7])?";
+
+        static Regex isINSEENumber = new Regex(String.Format(@"^(({0})|({1})){2}$", REGULAR_INSEE_NUMBER, TEMPORARY_INSEE_NUMBER, KEY_INSEE_NUMBER), RegexOptions.Compiled);
```
Comment (rducom) [inline NExtends/Primitives/String.extensions.cs]: all theses regex should be in another place I think. It's not really StringExtension methods, but more specific functional tests. We should provide another class for theses methods

**Comment by nfaugout** [comment]
@rducom thanks for review, can you create Issues for each of your points ?
